services:
  - type: web
    name: viorai-firebase-embedder
    env: python
    plan: starter
    buildCommand: ""
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/firebase-key.json